apiVersion: v1
kind: Service
metadata:
  name: collection-service
  labels:
    app: collection-service
spec:
  selector:
    app: collection-deployment
  ports:
    - protocol: TCP
      port: 8086
      targetPort: 8086
  type: LoadBalancer