apiVersion: v1
kind: Service
metadata:
  name: greaseandsolid-service
  labels:
    app: greaseandsolid-service
spec:
  selector:
    app: greaseandsolid-deployment
  ports:
    - protocol: TCP
      port: 8084
      targetPort: 8084
  type: LoadBalancer