apiVersion: v1
kind: Service
metadata:
  name: register-service
  labels:
    app: register-service
spec:
  selector:
    app: register-deployment
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
  type: LoadBalancer