apiVersion: apps/v1
kind: Deployment
metadata:
  name: collection-deployment
  labels:
    app: collection-deployment
spec:
  selector:
    matchLabels:
      app: collection-deployment
  replicas: 2
  template:
    metadata:
      labels:
        app: collection-deployment
    spec:
      containers:
        - name: collection
          image: nicolasvh/kubernetes-collection
          ports:
            - containerPort: 8081