apiVersion: apps/v1
kind: Deployment
metadata:
  name: greaseandsolid-deployment
  labels:
    app: greaseandsolid-deployment
spec:
  selector:
    matchLabels:
      app: greaseandsolid-deployment
  replicas: 2
  template:
    metadata:
      labels:
        app: greaseandsolid-deployment
    spec:
      containers:
        - name: greaseandsolid
          image: nicolasvh/kubernetes-greaseandsolid
          ports:
            - containerPort: 8081