apiVersion: v1
kind: Service
metadata:
  name: pay-service
  labels:
    app: pay-service
spec:
  selector:
    app: pay-deployment
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
  type: LoadBalancer