apiVersion: apps/v1
kind: Deployment
metadata:
  name: pay-deployment
  labels:
    app: pay-deployment
spec:
  selector:
    matchLabels:
      app: pay-deployment
  replicas: 2
  template:
    metadata:
      labels:
        app: pay-deployment
    spec:
      containers:
        - name: pay
          image: nicolasvh/kubernetes-pay
          ports:
            - containerPort: 8081