apiVersion: apps/v1
kind: Deployment
metadata:
  name: register-deployment
  labels:
    app: register-deployment
spec:
  selector:
    matchLabels:
      app: register-deployment
  replicas: 2
  template:
    metadata:
      labels:
        app: register-deployment
    spec:
      containers:
        - name: register
          image: nicolasvh/kubernetes-register
          ports:
            - containerPort: 8081